### ISSUE TITLE
Licensing is not clear

### ISSUE THREAD

**Issue by pellared** [aymanbagabas/go-udiff#2]
From https://cs.opensource.google/go/go/+/master:LICENSE

> Copyright (c) 2009 The Go Authors. All rights reserved.
> 
> Redistribution and use in source and binary forms, with or without
> modification, are permitted provided that the following conditions are
> met:
> 
>    * Redistributions of source code must retain the above copyright
> notice, this list of conditions and the following disclaimer.

I suggest doing something similar to:

https://github.com/goyek/goyek/blob/69dd3ded7471fd2250a68742591aad2d579cfe95/LICENSE#L23-L30

Right, now there are two licenses. It is not clear which should be followed (guessing that both).

**Comment by aymanbagabas** [comment]
Hi, @pellared. Files imported from Golang still retain the copyrights at the beginning of the file. That's why there are two licenses, they should be followed.
