### ISSUE TITLE
Feature: control number of surrounding lines

### ISSUE THREAD

**Issue by neilotoole** [aymanbagabas/go-udiff#5]
Thanks for a great library, it works perfectly.

Is it possible to add the ability to control the number of surrounding lines? E.g. with `git diff`:

```shell
# Show 7 lines instead of the default 3
$ git diff --unified=7
```

**Comment by aymanbagabas** [comment]
Hi @neilotoole, this feature has been implemented upstream. It's going to be part of the next release of `go-udiff` 🙂

**Comment by neilotoole** [comment]
@aymanbagabas Wonderful! I had made a private fork just for this functionality, now I can get rid of that 👍

If you're curious, check out what I was using it for here: https://sq.io/docs/diff
